start = input('programme ready to start')
if start == 'start' :
    print('programme starting')
    file = open('-@#.txt','w')
    file.write('hahahahaha\n'*20)
    file.close()    
    file1 = open('-@#1.txt','w')
    file1.write('hahahahaha\n'*20)
    file1.close()    
    file2 = open('-@#2.txt','w')
    file2.write('hahahahaha\n'*20)
    file2.close()    
    file3 = open('-@#3.txt','w')
    file3.write('hahahahaha\n'*20)
    file3.close()    
    file4 = open('-@#4.txt','w')
    file4.write('hahahahaha\n'*20)
    file4.close()    
    file5 = open('-@#5.txt','w')
    file5.write('hahahahaha\n'*20)
    file5.close()    
    file6 = open('-@#6.txt','w')
    file6.write('hahahahaha\n'*20)
    file6.close()    
